name: Run Telegram Bot

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: pip install telethon openai schedule nbconvert
        
    - name: Convert notebook to script
      run: jupyter nbconvert --to python telegram_bot.ipynb
        
    - name: Run Telegram Bot
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
        AFFILIATE_LINK: ${{ secrets.AFFILIATE_LINK }}
      run: python telegram_bot.py
